# Generated by Django 6.0.4 on 2026-04-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='alert_threshold',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='budget',
            name='last_notified_threshold',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
