# Generated by Django 6.0.4 on 2026-04-13 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_otpverification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTPVerification',
        ),
    ]
